name: Python CI/CD Pipeline

# 🏁 Define when the workflow should run
on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Runs on pull request events targeting main

jobs:
  test:  # Define the test job
    runs-on: ubuntu-latest  # Use an Ubuntu virtual machine

    steps:
      # 1️⃣ Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3  # Predefined GitHub action to clone repo

      # 2️⃣ Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify Python version

      # 3️⃣ Install dependencies
      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # 4️⃣ Run Unit Tests
      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest tests/
